import sys
sys.path.append(".")

from app.database import SessionLocal, engine, Base
from app.models.merkez import Merkez

# Créer les tables
Base.metadata.create_all(bind=engine)

def seed_professeurs():
    db = SessionLocal()

    # Vider la table d'abord
    db.query(Merkez).delete()
    db.commit()

    professeurs = [
        {
            "nom": "Cheikh Ahmed Al-Mansouri",
            "email": "ahmed.mansouri@maraakiz.com",
            "telephone": "+33 6 12 34 56 78",
            "bio": "Diplômé de l'Université Al-Azhar, j'enseigne le Coran et le Tajwid depuis 15 ans. Ma méthode allie rigueur et bienveillance pour un apprentissage efficace.",
            "image_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop",
            "matieres": ["coran", "tajwid"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant", "intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["enfants", "ados", "hommes", "femmes"],
            "prix_min": 20.0,
            "prix_max": 30.0,
            "premier_cours_gratuit": True,
            "ville": "Paris",
            "pays": "France",
            "note_moyenne": 4.9,
            "nombre_avis": 127,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 45,
            "nombre_cours_donnes": 320
        },
        {
            "nom": "Oum Khadija",
            "email": "oum.khadija@maraakiz.com",
            "telephone": "+33 6 23 45 67 89",
            "bio": "Enseignante spécialisée dans l'apprentissage de l'arabe pour les francophones. Cours adaptés aux femmes et enfants avec une pédagogie douce.",
            "image_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=500&fit=crop",
            "matieres": ["arabe", "sciences"],
            "formats": ["en-ligne", "presentiel"],
            "niveaux": ["debutant", "intermediaire"],
            "langues": ["francais", "arabe"],
            "public_cible": ["femmes", "enfants"],
            "prix_min": 18.0,
            "prix_max": 25.0,
            "premier_cours_gratuit": False,
            "ville": "Lyon",
            "pays": "France",
            "note_moyenne": 5.0,
            "nombre_avis": 89,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 38,
            "nombre_cours_donnes": 215
        },
        {
            "nom": "Ustadh Bilal Ibrahim",
            "email": "bilal.ibrahim@maraakiz.com",
            "telephone": "+33 6 34 56 78 90",
            "bio": "Professeur trilingue (FR/AR/EN) spécialisé dans l'enseignement du Coran avec Tajwid. Méthode interactive et moderne pour tous niveaux.",
            "image_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&h=500&fit=crop",
            "matieres": ["coran", "arabe", "tajwid"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant", "intermediaire", "avance"],
            "langues": ["francais", "arabe", "anglais"],
            "public_cible": ["hommes", "ados", "enfants"],
            "prix_min": 25.0,
            "prix_max": 35.0,
            "premier_cours_gratuit": True,
            "ville": "Marseille",
            "pays": "France",
            "note_moyenne": 4.8,
            "nombre_avis": 203,
            "verifie": True,
            "actif": True,
            "nouveau": True,
            "nombre_eleves": 67,
            "nombre_cours_donnes": 450
        },
        {
            "nom": "Soeur Fatima Zahra",
            "email": "fatima.zahra@maraakiz.com",
            "telephone": "+33 6 45 67 89 01",
            "bio": "Mémorisation du Coran et apprentissage de l'arabe pour les soeurs. Cours en petits groupes ou individuels, ambiance familiale.",
            "image_url": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&h=500&fit=crop",
            "matieres": ["coran", "arabe"],
            "formats": ["en-ligne", "presentiel"],
            "niveaux": ["debutant", "intermediaire"],
            "langues": ["francais", "arabe"],
            "public_cible": ["femmes"],
            "prix_min": 15.0,
            "prix_max": 22.0,
            "premier_cours_gratuit": True,
            "ville": "Toulouse",
            "pays": "France",
            "note_moyenne": 4.9,
            "nombre_avis": 156,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 42,
            "nombre_cours_donnes": 298
        },
        {
            "nom": "Cheikh Youssef Al-Jazairi",
            "email": "youssef.jazairi@maraakiz.com",
            "telephone": "+33 6 56 78 90 12",
            "bio": "Spécialiste en sciences religieuses (Fiqh, Hadith, Tafsir). Cours approfondis pour niveaux avancés. Diplômé de Médine.",
            "image_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&h=500&fit=crop",
            "matieres": ["sciences"],
            "formats": ["en-ligne"],
            "niveaux": ["intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes", "femmes"],
            "prix_min": 30.0,
            "prix_max": 40.0,
            "premier_cours_gratuit": False,
            "ville": "Lille",
            "pays": "France",
            "note_moyenne": 4.7,
            "nombre_avis": 94,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 28,
            "nombre_cours_donnes": 187
        },
        {
            "nom": "Professeur Karim Ben Ali",
            "email": "karim.benali@maraakiz.com",
            "telephone": "+33 6 67 89 01 23",
            "bio": "Enseignant d'arabe littéraire et dialectal. Méthode communicative pour progresser rapidement à l'oral comme à l'écrit.",
            "image_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&h=500&fit=crop",
            "matieres": ["arabe"],
            "formats": ["en-ligne", "presentiel"],
            "niveaux": ["debutant", "intermediaire"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes", "femmes", "ados"],
            "prix_min": 18.0,
            "prix_max": 28.0,
            "premier_cours_gratuit": True,
            "ville": "Nice",
            "pays": "France",
            "note_moyenne": 4.6,
            "nombre_avis": 72,
            "verifie": True,
            "actif": True,
            "nouveau": True,
            "nombre_eleves": 31,
            "nombre_cours_donnes": 165
        },
        {
            "nom": "Oum Maryam Al-Andalusi",
            "email": "oum.maryam@maraakiz.com",
            "telephone": "+33 6 78 90 12 34",
            "bio": "Spécialisée dans l'enseignement du Coran pour enfants avec méthodes ludiques et interactives. 10 ans d'expérience.",
            "image_url": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=500&h=500&fit=crop",
            "matieres": ["coran", "tajwid"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant"],
            "langues": ["francais", "arabe"],
            "public_cible": ["enfants"],
            "prix_min": 12.0,
            "prix_max": 18.0,
            "premier_cours_gratuit": True,
            "ville": "Nantes",
            "pays": "France",
            "note_moyenne": 5.0,
            "nombre_avis": 134,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 56,
            "nombre_cours_donnes": 412
        },
        {
            "nom": "Cheikh Omar Fathi",
            "email": "omar.fathi@maraakiz.com",
            "telephone": "+33 6 89 01 23 45",
            "bio": "Hafidh du Coran, j'accompagne mes élèves dans la mémorisation complète. Programme personnalisé selon votre rythme.",
            "image_url": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&h=500&fit=crop",
            "matieres": ["coran", "tajwid"],
            "formats": ["en-ligne", "presentiel"],
            "niveaux": ["intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes", "ados"],
            "prix_min": 22.0,
            "prix_max": 32.0,
            "premier_cours_gratuit": False,
            "ville": "Strasbourg",
            "pays": "France",
            "note_moyenne": 4.8,
            "nombre_avis": 118,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 39,
            "nombre_cours_donnes": 267
        },
        {
            "nom": "Institut Nour Al-Ilm",
            "email": "contact@nour-ilm.fr",
            "telephone": "+33 6 90 12 34 56",
            "bio": "Institut d'enseignement islamique offrant des cours collectifs de Coran, arabe et sciences religieuses. Équipe pédagogique qualifiée.",
            "image_url": "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=500&h=500&fit=crop",
            "matieres": ["coran", "arabe", "tajwid", "sciences"],
            "formats": ["presentiel", "en-ligne"],
            "niveaux": ["debutant", "intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes", "femmes", "enfants", "ados"],
            "prix_min": 10.0,
            "prix_max": 20.0,
            "premier_cours_gratuit": True,
            "ville": "Bordeaux",
            "pays": "France",
            "note_moyenne": 4.7,
            "nombre_avis": 245,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 187,
            "nombre_cours_donnes": 1240
        },
        {
            "nom": "Soeur Aisha Mahmoud",
            "email": "aisha.mahmoud@maraakiz.com",
            "telephone": "+33 6 01 23 45 67",
            "bio": "Cours d'arabe pour débutantes avec support pédagogique complet. Ambiance bienveillante et motivante.",
            "image_url": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&h=500&fit=crop",
            "matieres": ["arabe"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant"],
            "langues": ["francais", "arabe"],
            "public_cible": ["femmes"],
            "prix_min": 16.0,
            "prix_max": 22.0,
            "premier_cours_gratuit": True,
            "ville": "Montpellier",
            "pays": "France",
            "note_moyenne": 4.9,
            "nombre_avis": 81,
            "verifie": True,
            "actif": True,
            "nouveau": True,
            "nombre_eleves": 29,
            "nombre_cours_donnes": 143
        },
        {
            "nom": "Professeur Hassan Al-Maghribi",
            "email": "hassan.maghribi@maraakiz.com",
            "telephone": "+33 6 12 45 78 90",
            "bio": "Expert en Tajwid et récitation coranique. Cours individuels ou en binôme pour perfectionner votre prononciation.",
            "image_url": "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&h=500&fit=crop",
            "matieres": ["tajwid", "coran"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant", "intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes", "femmes", "ados"],
            "prix_min": 20.0,
            "prix_max": 28.0,
            "premier_cours_gratuit": False,
            "ville": "Rennes",
            "pays": "France",
            "note_moyenne": 4.8,
            "nombre_avis": 97,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 34,
            "nombre_cours_donnes": 219
        },
        {
            "nom": "Oum Hafsa",
            "email": "oum.hafsa@maraakiz.com",
            "telephone": "+33 6 23 56 89 01",
            "bio": "Cours de Coran et arabe pour les petits (4-10 ans). Méthode Montessori adaptée à l'enseignement islamique.",
            "image_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&h=500&fit=crop",
            "matieres": ["coran", "arabe"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant"],
            "langues": ["francais"],
            "public_cible": ["enfants"],
            "prix_min": 14.0,
            "prix_max": 20.0,
            "premier_cours_gratuit": True,
            "ville": "Angers",
            "pays": "France",
            "note_moyenne": 5.0,
            "nombre_avis": 112,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 47,
            "nombre_cours_donnes": 334
        },
        {
            "nom": "Cheikh Abdallah Soudani",
            "email": "abdallah.soudani@maraakiz.com",
            "telephone": "+33 6 34 67 90 12",
            "bio": "Enseignement des sciences islamiques (Aquida, Fiqh, Hadith). Cours structurés basés sur les textes authentiques.",
            "image_url": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&h=500&fit=crop",
            "matieres": ["sciences"],
            "formats": ["en-ligne", "presentiel"],
            "niveaux": ["intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes"],
            "prix_min": 28.0,
            "prix_max": 38.0,
            "premier_cours_gratuit": False,
            "ville": "Grenoble",
            "pays": "France",
            "note_moyenne": 4.9,
            "nombre_avis": 76,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 23,
            "nombre_cours_donnes": 156
        },
        {
            "nom": "Soeur Yasmine Khelifi",
            "email": "yasmine.khelifi@maraakiz.com",
            "telephone": "+33 6 45 78 01 23",
            "bio": "Professeure d'arabe diplômée. Cours dynamiques avec exercices pratiques et supports audio. Tous niveaux bienvenus.",
            "image_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&h=500&fit=crop",
            "matieres": ["arabe"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant", "intermediaire", "avance"],
            "langues": ["francais", "arabe"],
            "public_cible": ["femmes", "ados"],
            "prix_min": 17.0,
            "prix_max": 24.0,
            "premier_cours_gratuit": True,
            "ville": "Tours",
            "pays": "France",
            "note_moyenne": 4.7,
            "nombre_avis": 68,
            "verifie": True,
            "actif": True,
            "nouveau": True,
            "nombre_eleves": 27,
            "nombre_cours_donnes": 148
        },
        {
            "nom": "Ustadh Mohammed Salah",
            "email": "mohammed.salah@maraakiz.com",
            "telephone": "+33 6 56 89 12 34",
            "bio": "Cours de Coran avec Tajwid pour adolescents et adultes. Suivi personnalisé et révisions régulières. Ambiance studieuse.",
            "image_url": "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=500&h=500&fit=crop",
            "matieres": ["coran", "tajwid"],
            "formats": ["en-ligne"],
            "niveaux": ["debutant", "intermediaire"],
            "langues": ["francais", "arabe"],
            "public_cible": ["hommes", "ados"],
            "prix_min": 19.0,
            "prix_max": 27.0,
            "premier_cours_gratuit": True,
            "ville": "Dijon",
            "pays": "France",
            "note_moyenne": 4.6,
            "nombre_avis": 54,
            "verifie": True,
            "actif": True,
            "nouveau": False,
            "nombre_eleves": 21,
            "nombre_cours_donnes": 132
        }
    ]

    # Insérer les professeurs
    for prof_data in professeurs:
        prof = Merkez(**prof_data)
        db.add(prof)

    db.commit()
    print(f"✅ {len(professeurs)} professeurs insérés avec succès !")
    db.close()

if __name__ == "__main__":
    seed_professeurs()
